- hosts: localhost # Kubectl is configured from this machine
  roles:
    - deploy_DB_longhorn
    - deploy_harbor
  vars:

    # Helm chart version for harbor 
    harbor_version: "1.10.2" 
    longhorn_version: "1.3.2"

    # Name of harbor cluster used in load balancer names
    harbor_cluster_name: harbor-cluster
    # K8s namespace
    harbor_namespace: harbor
    # Helm name of the service
    harbor_deployed_name: harbor

    db_host_name: 
    db_user_name: 
